model:
  path: "keyword_spotting/weights/checkpoint.tflite"
  confidence: 0.95
  labels: ["background", "marvin"]
ros:
  publish_topic: "/voice/command"
  inference_topic: "/voice/inference"
  publish_inference: true
  audio_topic: "/audio/raw"
